-- MySQL Script generated by MySQL Workbench
-- Wed Mar 11 13:45:43 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Alumno` (
  `email_alumno` INT NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `numero_cuenta` VARCHAR(45) NOT NULL,
  `carrera` VARCHAR(45) NOT NULL,
  `credito` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `historial_academico` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email_alumno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Videojuego`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Videojuego` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Videojuego` (
  `idVideojuego` INT NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `ruta_almacenamiento` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `portada` VARCHAR(45) NOT NULL,
  `título` VARCHAR(45) NOT NULL,
  `descripción` VARCHAR(45) NOT NULL,
  `Ruta_juego` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVideojuego`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Descargar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Descargar` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Descargar` (
  `email_alumno` INT NOT NULL,
  `id_videojuego` VARCHAR(45) NOT NULL,
  CONSTRAINT `email_alumno`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Alumno` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_videojuego`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Videojuego` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Administrador` (
  `email_admin` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `email_contacto` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email_admin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Otorgar_prestamo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Otorgar_prestamo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Otorgar_prestamo` (
  `email_alumno` INT NOT NULL,
  `email_admin` VARCHAR(45) NOT NULL,
  `cantidad_credito` VARCHAR(45) NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `aprobado` VARCHAR(45) NOT NULL,
  CONSTRAINT `email_alumno`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Alumno` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `email_admin`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Administrador` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ofrecer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ofrecer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ofrecer` (
  `email_admin` INT NOT NULL,
  `id_videojuego` VARCHAR(45) NOT NULL,
  CONSTRAINT `email_admin`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Administrador` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_videojuego`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Videojuego` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
