/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-14 03:07:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n");
      out.write("  <link rel=\"icon\" type=\"image/vnd.microsoft.icon\" href=\"public/img/favicon.png\"/>\n");
      out.write("  <title>Pulse Games</title>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"public/css/bootstrap.css\">\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"public/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <nav class=\"navbar navbar-default\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <div class=\"navbar-header\">\n");
      out.write("        <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("          <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("        <ul class=\"nav navbar-nav pull-right\">\n");
      out.write("          <li><a href=\"#\">Iniciar Sesión</a></li>\n");
      out.write("          <li><a href=\"#\">Registrarse</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("  <div id=\"logo\" class=\"row\">\n");
      out.write("    <svg viewBox=\"20 20 600 300\">\n");
      out.write("\n");
      out.write("        <!-- Symbol with text -->\n");
      out.write("        <symbol id=\"s-text\">\n");
      out.write("          <text text-anchor=\"middle\"\n");
      out.write("          x=\"50%\"\n");
      out.write("          y=\"50%\"\n");
      out.write("          dy=\".35em\"\n");
      out.write("          class=\"text\"\n");
      out.write("          >\n");
      out.write("          Pulse Games\n");
      out.write("          </text>    \n");
      out.write("        </symbol>\n");
      out.write("\n");
      out.write("      <!--Mask-->\n");
      out.write("      <mask id=\"m-text\"\n");
      out.write("        maskunits=\"userSpaceOnUse\"\n");
      out.write("        maskcontentunits=\"userSpaceOnUse\">\n");
      out.write("        <use xlink:href=\"#s-text\"\n");
      out.write("        class=\"text-mask\">\n");
      out.write("        </use>\n");
      out.write("      </mask>\n");
      out.write("\n");
      out.write("      <!-- Group with mask -->\n");
      out.write("      <g mask=\"url(#m-text)\">\n");
      out.write("      <!-- Masked content -->\n");
      out.write("        <!-- http://tympanus.net/codrops-playground/assets/images/posts/23145/image2.jpg -->\n");
      out.write("        <image xlink:href=\"public/img/morado.jpg\"\n");
      out.write("        width=\"900\"\n");
      out.write("        height=\"532\"\n");
      out.write("        x=\"-30%\"\n");
      out.write("        y=\"-20%\">\n");
      out.write("        </image>\n");
      out.write("      </g>\n");
      out.write("    </svg>\n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("  <div class=\"container\">\n");
      out.write("<!--   <div id=\"entrar_row\" class=\"row-fluid\">\n");
      out.write("    <div class=\"col-md-5\"></div>\n");
      out.write("    <button class=\"button button--nina button--border-thin button--round-s\" data-text=\"Entrar\">\n");
      out.write("    <span>E</span><span>n</span><span>t</span><span>r</span><span>a</span><span>r</span>\n");
      out.write("    </button>\n");
      out.write("  </div>\n");
      out.write(" -->  \n");
      out.write("  </div>\n");
      out.write("  <script type=\"text/javascript\" src=\"public/js/jquery-2.1.3.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"public/js/bootstrap.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"public/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
