/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-14 04:02:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/videojuegos.jsp", Long.valueOf(1426305702000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"/>\n");
      out.write("  <link rel=\"icon\" type=\"image/vnd.microsoft.icon\" href=\"public/img/favicon.png\"/>\n");
      out.write("  <title>Pulse Games</title>\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"public/css/bootstrap.css\">\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"public/css/style.css\">\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"public/css/inside.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <nav class=\"navbar navbar-default\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <div class=\"navbar-header\">\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">\n");
      out.write("          <img id=\"brand\" alt=\"pulsegames\" src=\"public/img/logo.png\">\n");
      out.write("        </a>\n");
      out.write("        <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("          <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("          <span class=\"icon-bar\"></span>\n");
      out.write("        </button>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("        <ul class=\"nav navbar-nav pull-right\">\n");
      out.write("          <li><a href=\"#\">Iniciar Sesión</a></li>\n");
      out.write("          <li><a href=\"#\">Registrarse</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("  \n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("#pad{\n");
      out.write("  padding-left: 10em;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<div id=\"carousel-example-generic\" class=\"carousel slide\" data-ride=\"carousel\">\n");
      out.write("    <!-- Indicators -->\n");
      out.write("    <div class=\"carousel-indicators\">\n");
      out.write("      <div  data-target=\"#carousel-example-generic\" data-slide-to=\"0\" class=\"pad\">\n");
      out.write("        <img src=\"public/img/morado.jpg\" style=\"width:10em; margin: auto !important;\">\n");
      out.write("      </div>\n");
      out.write("      <div data-target=\"#carousel-example-generic\" data-slide-to=\"1\"class=\"pad\">\n");
      out.write("        <img src=\"public/img/morado.jpg\" style=\"width:10em;margin: auto !important;\">\n");
      out.write("      </div>\n");
      out.write("      <div data-target=\"#carousel-example-generic\" data-slide-to=\"2\"class=\"pad\">\n");
      out.write("        <img src=\"public/img/morado.jpg\" style=\"width:10em;margin: auto !important;\">\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Wrapper for slides -->\n");
      out.write("    <div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("      <div class=\"item active row\">\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <img  src=\"public/img/morado.jpg\" alt=\"...\">\n");
      out.write("        </div>\n");
      out.write("        <div style=\"padding-left:3em;\"class=\"col-md-6\">\n");
      out.write("          <h1>Videojuego de Muestra 1</h1>\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("     <div class=\"item  row\">\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <img  src=\"public/img/morado.jpg\" alt=\"...\">\n");
      out.write("        </div>\n");
      out.write("        <div style=\"padding-left:3em;\"class=\"col-md-6\">\n");
      out.write("          <h1>Videojuego de Muestra 2</h1>\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"item  row\">\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <img  src=\"public/img/morado.jpg\" alt=\"...\">\n");
      out.write("        </div>\n");
      out.write("        <div style=\"padding-left:3em;\"class=\"col-md-6\">\n");
      out.write("          <h1>Videojuego de Muestra 3</h1>\n");
      out.write("        </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Controls -->\n");
      out.write("    <a class=\"left carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"prev\">\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\n");
      out.write("      <span class=\"sr-only\">Previous</span>\n");
      out.write("    </a>\n");
      out.write("    <a class=\"right carousel-control\" href=\"#carousel-example-generic\" role=\"button\" data-slide=\"next\">\n");
      out.write("      <span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\n");
      out.write("      <span class=\"sr-only\">Next</span>\n");
      out.write("    </a>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  \n");
      out.write("  <nav class=\"navbar navbar-default navbar-fixed-bottom\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\n");
      out.write("        <ul class=\"nav navbar-nav pull-left\">\n");
      out.write("          <li><a href=\"#\">Contacto</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("  <script type=\"text/javascript\" src=\"public/js/jquery-2.1.3.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"public/js/bootstrap.min.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"public/js/main.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
