/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.59
 * Generated at: 2015-03-11 22:50:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <meta charset=\"utf-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"user-scalable=no, width=device-width, initial-scale=1\">\n");
      out.write("        <title>Converse Made By You</title>\n");
      out.write("        <meta property=\"og:title\" content=\"Converse Made By You\">\n");
      out.write("        <meta property=\"og:description\" content=\"Converse Made By You\">\n");
      out.write("        <meta property=\"og:type\" content=\"web\">\n");
      out.write("        <meta property=\"og:image\" content=\"/img/ogp_converse.png\">\n");
      out.write("        <meta name=\"description\" content=\"Converse Made By You\">\n");
      out.write("        <meta name=\"keywords\" content=\"Converse, tenis converse\">\n");
      out.write("        <link href=\"css/converse.css\" media=\"screen\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link href=\"css/responsive.css\" media=\"screen\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link href=\"lib/owl-carousel/assets/owl.carousel.css\" media=\"screen\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link href=\"lib/owl-carousel/owl.theme.css\" media=\"screen\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("        <link rel=\"shortcut icon\" href=\"img/favicon.ico\"/>\n");
      out.write("        <script>\n");
      out.write("            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n");
      out.write("            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n");
      out.write("            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n");
      out.write("            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n");
      out.write("\n");
      out.write("            ga('create', 'UA-60104941-1', 'auto');\n");
      out.write("            ga('send', 'pageview');\n");
      out.write("\n");
      out.write("        </script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <nav>\n");
      out.write("            <div>\n");
      out.write("                    <div class=\"logo nav\">\n");
      out.write("                        <a onclick=\"ga('send', 'event', 'Menú', 'Boton', 'Logo')\" target=\"_blank\" href=\"http://www.converse.com.mx/principalAlt\">\n");
      out.write("                        <img src=\"img/logo.png\">\n");
      out.write("                        </a>\n");
      out.write("                    </div>\n");
      out.write("                \n");
      out.write("                <div id=\"social\" class=\"nav\">\n");
      out.write("                    <a onclick=\"ga('send', 'event', 'Menú', 'Boton', 'FB')\" target=\"blank\" href=\"https://www.facebook.com/converse\" class=\"socicon\">b</a>\n");
      out.write("                    <a onclick=\"ga('send', 'event', 'Menú', 'Boton', 'TW')\" target=\"blank\" href=\"https://twitter.com/Converse_Mexico\" class=\"socicon\">a</a>\n");
      out.write("                    <a onclick=\"ga('send', 'event', 'Menú', 'Boton', 'Instragram')\" target=\"blank\" href=\"https://instagram.com/conversemexico/\" class=\"socicon\">x</a>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"main\" class=\"nav hidden_desktop\">\n");
      out.write("                    <p id=\"link_video\" class=\"links_nav\" onclick=\"autoScroll('video'), ga('send', 'event', 'Menú', 'Boton', 'Video') \">Video</p>\n");
      out.write("                    <p id=\"link_gallery\" class=\"links_nav\" onclick=\"autoScroll('slide'), ga('send', 'event', 'Menú', 'Boton', 'Galería')\">Galería</p>\n");
      out.write("                    <p id=\"link_redes\" class=\"links_nav\" onclick=\"autoScroll('fade'), ga('send', 'event', 'Menú', 'Boton', '#ChuckTaylor')\">#ChuckTaylor</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <section id=\"video\" class=\"show\">\n");
      out.write("            <div class=\"section\">\n");
      out.write("                <div id=\"cont_video\">\n");
      out.write("                    <iframe width=\"1280\" height=\"720\" src=\"https://www.youtube.com/embed/n2CCz4x2xGE?rel=0\" frameborder=\"0\" allowfullscreen></iframe>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"baja0\" class=\"btn_baja\" onclick=\"autoScroll('slide')\">\n");
      out.write("                    <img src=\"img/baja.png\">\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <section id=\"slide\" class=\"show\">\n");
      out.write("            <div class=\"section\">\n");
      out.write("                <div id=\"owl-slider\" class=\"owl-carousel\">\n");
      out.write("                    \n");
      out.write("            </div>            \n");
      out.write("        </section>\n");
      out.write("        <section id=\"data\">\n");
      out.write("            <div class=\"section\">\n");
      out.write("                <div id=\"data_img\">\n");
      out.write("                    <img id=\"img_back\" src=\"img/tenis_big/tenisconverse007.jpg\">\n");
      out.write("                    <img src=\"img/tenis_big/tenisconverse007.jpg\">\n");
      out.write("                </div>\n");
      out.write("                <div id=\"data_text\" class=\"centerV_relative\" load=\"text_alt()\">\n");
      out.write("                    <div id=\"contText\">\n");
      out.write("                        <p id=\"data_desc\">“Backyard pool skating wah-wah pedal abuse.”</p>\n");
      out.write("                        <p id=\"data_autor\">Made by The Shrine</p>\n");
      out.write("                        <div class=\"compartir\">\n");
      out.write("                            <p><b>Compartir: </b></tp>\n");
      out.write("                            <p class=\"socicon\" onclick=\"share_fb(), ga('send', 'event', 'Historias', 'Compartir FB', ''+ $('#data_autor').text() +'')\">b</p>\n");
      out.write("                            <p class=\"socicon\" onclick=\"share_tw(), ga('send', 'event', 'Historias', 'Compartir TW', ''+ $('#data_autor').text() +'')\">a</p>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"controls\"><div class=\"buttons\"><div class=\"prev\"><img src=\"img/arrow_left.png\"></div><div class=\"next\"><img src=\"img/arrow_right.png\"></div></div></div>\n");
      out.write("        </section>\n");
      out.write("        <section id=\"fade\" class=\"show\">\n");
      out.write("            <p id=\"title_sec\">#ChuckTaylor</p>\n");
      out.write("            <div class=\"section\">\n");
      out.write("            </div>\n");
      out.write("        </section>\n");
      out.write("        <center>\n");
      out.write("            <img src=\"img/plus.png\" onclick=\"feed_plus(), scroll_notice(), ga('send', 'event', 'Menú', 'Boton', 'Recargar Más')\">\n");
      out.write("        </center>\n");
      out.write("        <footer>\n");
      out.write("            <a onclick=\"ga('send', 'event', 'Footer', 'Boton', 'Explora')\" target=\"_blank\" href=\"http://www.converse.com.mx/blog\"><p>EXPLORA</p></a>\n");
      out.write("            <a onclick=\"ga('send', 'event', 'Footer', 'Boton', 'Donde Comprar')\" target=\"_blank\" href=\"http://www.converse.com.mx/tiendas\"><p>¿DÓNDE COMPRAR?</p></a>\n");
      out.write("            <a onclick=\"ga('send', 'event', 'Footer', 'Boton', 'Contactanos')\" target=\"_blank\" href=\"http://www.converse.com.mx/comentarios\"><p>CONTÁCTANOS</p></a>\n");
      out.write("            <a onclick=\"ga('send', 'event', 'Footer', 'Boton', 'Quienes Somos')\" target=\"_blank\" href=\"http://www.converse.com.mx/acerca\"><p>¿QUIÉNES SOMOS?</p></a>\n");
      out.write("            <a onclick=\"ga('send', 'event', 'Footer', 'Boton', 'Politicas de Privacidad')\" target=\"_blank\" href=\"http://www.converse.com.mx/politicas\"><p>POLÍTICA DE PRIVACIDAD</p></a>\n");
      out.write("            <a onclick=\"ga('send', 'event', 'Footer', 'Boton', 'RSS')\" target=\"_blank\" href=\"http://www.converse.com.mx/rss\"><p>RSS</p></a>\n");
      out.write("            <a onclick=\"ga('send', 'event', 'Footer', 'Boton', 'Responsabilidad Social')\" target=\"_blank\" href=\"http://www.responsabilidadsocial.org.mx/tag/pintando-pasos/\"><p>RESPONSABILIDAD SOCIAL</p></a>\n");
      out.write("        </footer>\n");
      out.write("        <div id=\"fb-root\"></div>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/jquery-2.1.1.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/waypoints.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/converse.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"lib/owl-carousel/owl.carousel.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/social_twitter.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
